apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    name: guestbook
    component: frontend
spec:
  selector:
    matchLabels:
      name: guestbook
      component: frontend
  replicas: 2
  template:
    metadata:
      labels:
        name: guestbook
        component: frontend
    spec:
      containers:
      - name: guestbook
        image: 132804413725.dkr.ecr.us-east-1.amazonaws.com/webapp:v0.1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80
