apiVersion: v1
kind: Service
metadata:
  name: frontend-lb
spec:
  selector:
    name: guestbook
    component: frontend
    app: mysql
  ports:
    port: 80
    targetPort: 80
    protocol: TCP
  type: LoadBalancer
