apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    name: webapp
    component: frontend
spec:
  selector:
    matchLabels:
      name: webapp
      component: frontend
  replicas: 2
  template:
    metadata:
      labels:
        name: webapp
        component: frontend
    spec:
      containers:
      - name: webapp
        image: 132804413725.dkr.ecr.us-east-1.amazonaws.com/webapp:v0.1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
         env:
          - name: DBHOST
            value: "mysqldb.lab3"
          - name: DBPORT
            value: "3306"
          - name: DBUSER
            value: "root"
          - name: DBPWD
            value: "pass1234"
          - name: DATABASE
            value: "employees"
          - name: APP_COLOR
            value: "green"
        ports:
        - name: web
          containerPort: 8080
          protocol: TCP
