apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    name: mysql
    component: backend
spec:
  selector:
    matchLabels:
      name: mysql
      component: backend
  replicas: 1
  template:
    metadata:
      labels:
        name: mysql
        component: backend
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        args:
          - --bind_ip
          - 0.0.0.0
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
