apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    name: mysql
    component: backend
spec:
  serviceName: mysql
  replicas: 2
  selector:
    matchLabels:
      app: mysql # has to match .spec.template.metadata.labels
      component: backend
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - name: mysql
          containerPort: 3306
        volumeMounts:
        - name: mysql-persistant-storage
          mountPath: /var/lib/mysql
  volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
